#signal to noise generator using rnorm or normal noise
# siganl generated by
# Y=f(X)+??
# S/N given by Var(f(X))/Var(??)
#Smooothing dem using moving average and Savitisky_Golay
library("plotly")
signal_function  <- function(){
  x = seq(290,350,by=0.1)
  data1 <- (1000*dnorm(x, mean = 320, sd = 3.7))/(max(dnorm(x, mean = 320, sd = 3.7)))
  return (data1)
}
signal_and_noise_generator <- function(test_signal,SNR){
  noise = rnorm(test_signal) # generate standard normal errors
  k <- sqrt(var(test_signal)/(SNR*var(noise)))
  signal_Plus_noise <- k*noise + test_signal
  return (signal_Plus_noise)
}
smoothing_moving_average <- function(signal_SNR,coeffn){
  ma =  c(rep(1, coeffn))/coeffn
  #xx <- 1:100
  #stats::filter(xx, rep(1, 3), sides = 1)
  sn.ma25=stats::filter(signal_SNR,ma)
  return(sn.ma25)
}
smoothing_Savitisky_Golay <- function(signal_SNR){
  #sg5 = c(-3, 12, 17, 12, -3)/35 #5-point quadratic or cubic smoothing function come fro tables
  #sg9 = c(-21,14,39,54,59,57,39,14,-21)/231 #9-point quadratic or cubic smoothing function come fro tables
  sg13 = c(-11,0,9,16,21,24,25,21,16,9,0,-11)/143 #13-point quadratic or cubic smoothing function come fro tables
  sn.sg <- stats::filter(signal_SNR,sg13) 
  return(sn.sg)
}
#signal_SNR <- as.numeric(dfx[3:1026,2])

SNR = 10
test_signal <- signal_function()
signal_SNR <- signal_and_noise_generator(test_signal,SNR)
#smooth_siganl <- smoothing_Savitisky_Golay(signal_SNR)
smooth_siganl <- smoothing_moving_average(signal_SNR,25)
x = seq(290,350,by=0.1)
#x<- as.numeric(dfx[3:1026,1])
plot_ly(x= x,y= signal_SNR ,name = 'SNR',type="scatter",mode="lines")%>%
  add_trace(x= x,y = smooth_siganl, name = 'smooth signal', mode = "lines")

